using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace OOP.Code
{
    public static class Tarriffs
    {
        public static Dictionary<City, Dictionary<City, decimal>> ShippingRates = new Dictionary<City, Dictionary<City, decimal>>() {

            { City.Вінниця, new Dictionary<City, decimal> { { City.Вінниця, 0m }, { City.Дніпро, 64m }, { City.Донецьк, 86m }, { City.Запоріжжя, 74m }, { City.Київ, 25m }, { City.Кіровоград, 31m }, { City.Луганськ, 105m }, { City.Львів, 36m }, { City.Миколаїв, 47m }, { City.Одеса, 42m }, { City.Полтава, 59m }, { City.Суми, 60m }, { City.Харків, 73m }, { City.Херсон, 52m }, { City.Черкаси, 34m }, { City.Чернігів, 39m } } },
            { City.Дніпро, new Dictionary<City, decimal> { { City.Вінниця, 64m }, { City.Дніпро, 0m }, { City.Донецьк, 25m }, { City.Запоріжжя, 8m }, { City.Київ, 53m }, { City.Кіровоград, 29m }, { City.Луганськ, 39m }, { City.Львів, 97m }, { City.Миколаїв, 34m }, { City.Одеса, 46m }, { City.Полтава,19m }, { City.Суми, 43m }, { City.Харків, 21m }, { City.Херсон, 37m }, { City.Черкаси, 32m }, { City.Чернігів, 67m } } },
            { City.Донецьк, new Dictionary<City, decimal> { { City.Вінниця, 86m }, { City.Дніпро, 25m }, { City.Донецьк, 0m }, { City.Запоріжжя, 21m }, { City.Київ, 72m }, { City.Кіровоград, 52m }, { City.Луганськ, 14m }, { City.Львів, 122m }, { City.Миколаїв, 61m }, { City.Одеса, 73m }, { City.Полтава, 39m }, { City.Суми, 70m }, { City.Харків, 33m }, { City.Херсон, 56m }, { City.Черкаси, 54m }, { City.Чернігів, 86m } } },
            { City.Запоріжжя, new Dictionary<City, decimal> { { City.Вінниця, 74m }, { City.Дніпро, 8m }, { City.Донецьк, 21m }, { City.Запоріжжя, 0m }, { City.Київ, 60m }, { City.Кіровоград, 30m }, { City.Луганськ, 36m }, { City.Львів, 83m }, { City.Миколаїв, 37m }, { City.Одеса, 49m }, { City.Полтава, 27m }, { City.Суми, 47m }, { City.Харків, 28m }, { City.Херсон, 29m }, { City.Черкаси, 40m }, { City.Чернігів, 74m } } },
            { City.Київ, new Dictionary<City, decimal> { { City.Вінниця, 25m }, { City.Дніпро, 53m }, { City.Донецьк, 72m }, { City.Запоріжжя, 60m }, { City.Київ, 0m }, { City.Кіровоград, 29m }, { City.Луганськ, 81m }, { City.Львів, 55m }, { City.Миколаїв, 49m }, { City.Одеса, 48m }, { City.Полтава, 33m }, { City.Суми, 34m }, { City.Харків, 47m }, { City.Херсон, 55m }, { City.Черкаси, 19m }, { City.Чернігів, 14m } } },
            { City.Кіровоград, new Dictionary<City, decimal> { { City.Вінниця, 31m }, { City.Дніпро, 29m }, { City.Донецьк, 52m }, { City.Запоріжжя, 30m }, { City.Київ, 29m }, { City.Кіровоград, 0m }, { City.Луганськ, 66m }, { City.Львів, 71m }, { City.Миколаїв, 17m }, { City.Одеса, 29m }, { City.Полтава, 24m }, { City.Суми, 50m }, { City.Харків, 38m }, { City.Херсон, 22m }, { City.Черкаси, 12m }, { City.Чернігів, 36m } } },
            { City.Луганськ, new Dictionary<City, decimal> { { City.Вінниця, 105m }, { City.Дніпро, 39m }, { City.Донецьк, 14m }, { City.Запоріжжя, 36m }, { City.Київ, 81m }, { City.Кіровоград, 66m }, { City.Луганськ, 0m }, { City.Львів, 137m }, { City.Миколаїв, 85m }, { City.Одеса, 97m }, { City.Полтава, 47m }, { City.Суми, 25m }, { City.Харків, 33m }, { City.Херсон, 80m }, { City.Черкаси, 70m }, { City.Чернігів, 95m } } },
            { City.Львів, new Dictionary<City, decimal> { { City.Вінниця, 36m }, { City.Дніпро, 97m }, { City.Донецьк, 122m }, { City.Запоріжжя, 83m }, { City.Київ, 55m }, { City.Кіровоград, 71m }, { City.Луганськ, 137m }, { City.Львів, 0m }, { City.Миколаїв, 85m }, { City.Одеса, 97m }, { City.Полтава, 89m }, { City.Суми, 89m }, { City.Харків, 102m }, { City.Херсон, 114m }, { City.Черкаси, 74m }, { City.Чернігів, 69m } } },
            { City.Миколаїв, new Dictionary<City, decimal> { { City.Вінниця, 47m }, { City.Дніпро, 34m }, { City.Донецьк, 61m }, { City.Запоріжжя, 37m }, { City.Київ, 49m }, { City.Кіровоград, 17m }, { City.Луганськ, 85m }, { City.Львів, 85m }, { City.Миколаїв, 0m }, { City.Одеса, 12m }, { City.Полтава, 42m }, { City.Суми, 68m }, { City.Харків, 55m }, { City.Херсон, 5m }, { City.Черкаси, 30m }, { City.Чернігів, 64m } } },
            { City.Одеса, new Dictionary<City, decimal> { { City.Вінниця, 42m }, { City.Дніпро, 46m }, { City.Донецьк, 73m }, { City.Запоріжжя, 49m }, { City.Київ, 48m }, { City.Кіровоград, 29m }, { City.Луганськ, 97m }, { City.Львів, 97m }, { City.Миколаїв, 12m }, { City.Одеса, 0m }, { City.Полтава, 54m }, { City.Суми, 80m }, { City.Харків, 83m }, { City.Херсон, 17m }, { City.Черкаси, 42m }, { City.Чернігів, 52m } } },
            { City.Полтава, new Dictionary<City, decimal> { { City.Вінниця, 59m }, { City.Дніпро, 64m }, { City.Донецьк, 39m }, { City.Запоріжжя, 27m }, { City.Київ, 33m }, { City.Кіровоград, 24m }, { City.Луганськ, 47m }, { City.Львів, 89m }, { City.Миколаїв, 42m }, { City.Одеса, 54m }, { City.Полтава, 0m }, { City.Суми, 26m }, { City.Харків, 14m }, { City.Херсон, 47m }, { City.Черкаси, 27m }, { City.Чернігів, 47m } } },
            { City.Суми, new Dictionary<City, decimal> { { City.Вінниця, 60m }, { City.Дніпро, 64m }, { City.Донецьк, 70m }, { City.Запоріжжя, 47m }, { City.Київ, 34m }, { City.Кіровоград, 50m }, { City.Луганськ, 25m }, { City.Львів, 89m }, { City.Миколаїв, 68m }, { City.Одеса, 80m }, { City.Полтава, 36m }, { City.Суми, 0m }, { City.Харків, 19m }, { City.Херсон, 73m }, { City.Черкаси, 54m }, { City.Чернігів, 35m } } },
            { City.Харків, new Dictionary<City, decimal> { { City.Вінниця, 73m }, { City.Дніпро, 64m }, { City.Донецьк, 33m }, { City.Запоріжжя, 28m }, { City.Київ, 47m }, { City.Кіровоград, 38m }, { City.Луганськ, 33m }, { City.Львів, 102m }, { City.Миколаїв, 55m }, { City.Одеса, 83m }, { City.Полтава, 14m }, { City.Суми, 19m }, { City.Харків, 0m }, { City.Херсон, 57m }, { City.Черкаси, 42m }, { City.Чернігів, 60m } } },
            { City.Херсон, new Dictionary<City, decimal> { { City.Вінниця, 52m }, { City.Дніпро, 64m }, { City.Донецьк, 56m }, { City.Запоріжжя, 29m }, { City.Київ, 55m }, { City.Кіровоград, 22m }, { City.Луганськ, 80m }, { City.Львів, 114m }, { City.Миколаїв, 5m }, { City.Одеса, 17m }, { City.Полтава, 47m }, { City.Суми, 73m }, { City.Харків, 57m }, { City.Херсон, 0m }, { City.Черкаси, 35m }, { City.Чернігів, 69m } } },
            { City.Черкаси, new Dictionary<City, decimal> { { City.Вінниця, 34m }, { City.Дніпро, 32m }, { City.Донецьк, 54m }, { City.Запоріжжя, 40m }, { City.Київ, 19m }, { City.Кіровоград, 12m }, { City.Луганськ, 70m }, { City.Львів, 74m }, { City.Миколаїв, 30m }, { City.Одеса, 42m }, { City.Полтава, 27m }, { City.Суми, 54m }, { City.Харків, 42m }, { City.Херсон, 35m }, { City.Черкаси, 0m }, { City.Чернігів, 33m } } },
            { City.Чернігів, new Dictionary<City, decimal> { { City.Вінниця, 39m }, { City.Дніпро, 67m }, { City.Донецьк, 86m }, { City.Запоріжжя, 74m }, { City.Київ, 14m }, { City.Кіровоград, 36m }, { City.Луганськ, 95m }, { City.Львів, 69m }, { City.Миколаїв, 64m }, { City.Одеса, 52m }, { City.Полтава, 47m }, { City.Суми, 35m }, { City.Харків, 60m }, { City.Херсон, 69m }, { City.Черкаси, 33m }, { City.Чернігів, 0m } } },
        };
    } 
}
